# Generated by Django 3.1.8 on 2021-04-14 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0017_auto_20210414_1603'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_seo_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SEO_Page',
            new_name='SEOPage',
        ),
    ]
