# Generated by Django 3.1.8 on 2021-04-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('core', '0003_auto_20210414_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='summary',
            field=models.TextField(default='test', help_text='A summary of the page to be used on index pages.                      If Search Description is left blank, this text will be used on searh results and link previews.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seopage',
            name='search_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search Image'),
        ),
    ]
