# Generated by Django 3.1.8 on 2021-04-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0018_auto_20210415_1422'),
        ('core', '0005_auto_20210415_1422'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOPage',
        ),
    ]
