# Generated by Django 3.1.8 on 2021-04-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='seopage',
            name='search_image',
        ),
    ]
