# Generated by Django 3.1.8 on 2021-04-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('core', '0008_auto_20210415_1428'),
        ('home', '0020_auto_20210415_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOPage',
        ),
    ]
