# Generated by Django 3.1.8 on 2021-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_seopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(help_text='Name of referee', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_description',
            field=models.CharField(blank=True, help_text="Optional - Brief description of referee ('Mother of a student' etc)", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='reference_text',
            field=models.TextField(help_text='Reference text', max_length=800),
        ),
    ]
