# Generated by Django 3.1.8 on 2021-04-30 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('contact', '0002_auto_20210430_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={},
        ),
        migrations.AddField(
            model_name='formfield',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfield',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('url', 'URL'), ('checkbox', 'Checkbox')], max_length=16, verbose_name='Field Type'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('translation_key', 'locale')},
        ),
    ]
