# Generated by Django 3.1.8 on 2021-04-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210430_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='translation_key',
        ),
    ]
