# Generated by Django 3.1.8 on 2021-04-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20210430_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_error_warning',
            field=models.CharField(default='There was a problem submitting the form. Please check below and try again.', help_text='Text to display above the form in case there was a problem', max_length=80, verbose_name='Form Error Warning'),
        ),
    ]
