# Generated by Django 3.1.8 on 2021-05-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_contactpage_form_error_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='reply_to',
            field=models.EmailField(default='info@helenerodenposzler.com', max_length=254, verbose_name='Reply-to Email Address'),
            preserve_default=False,
        ),
    ]
