# Generated by Django 3.1.8 on 2021-05-02 08:28

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_contactpage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='receipt_email_content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Content for email sent to client', verbose_name='Receipt Email Content'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='receipt_email_subject',
            field=models.CharField(default='thank you', help_text='Subject for email sent to client', max_length=80, verbose_name='Receipt Email Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='reply_to',
            field=models.EmailField(help_text='Where to send replies made to the receipt email', max_length=254, verbose_name='Reply-to Email Address'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(verbose_name='Acknowledgement Text to Display After Submit'),
        ),
    ]
