# Generated by Django 3.1.8 on 2021-05-02 08:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20210502_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='receipt_email_content',
            field=wagtail.core.fields.RichTextField(help_text='Content for email sent to client', verbose_name='Receipt Email Content'),
        ),
    ]
