# Generated by Django 3.1.8 on 2021-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20210502_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='from_address',
            field=models.CharField(help_text='Address to send emails from. Account in email settings must have rights to use this address.', max_length=255, verbose_name='From Address'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='to_address',
            field=models.CharField(help_text='Address to send form submissions to. Separate multiple addresses by comma.', max_length=255, verbose_name='To Address'),
        ),
    ]
