# Generated by Django 3.1.8 on 2021-05-02 12:18

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_auto_20210502_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='subject',
            field=models.CharField(help_text='Subject Line for Notification Email. Will be suffixed by Date/Time.', max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(verbose_name='Acknowledgement Text to Display On Website After Submit'),
        ),
    ]
