# Generated by Django 3.1.8 on 2021-05-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_auto_20210502_1432'),
        ('contact', '0016_auto_20210502_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='receipt_email_footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='site_settings.emailsignature'),
        ),
    ]
