# Generated by Django 3.1.8 on 2021-05-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_contactpage_receipt_email_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['sort_order']},
        ),
    ]
