# Generated by Django 3.1.8 on 2021-05-03 13:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtailmetadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0002_auto_20210503_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(help_text='A summary of the page to be used on index pages.                      If Search Description is left blank, this text will be used on searh results and link previews.')),
                ('introduction', models.TextField(blank=True)),
                ('search_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
