# Generated by Django 3.1.8 on 2021-05-03 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0003_auto_20210503_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPostPage',
            new_name='BlogDetailPage',
        ),
        migrations.RemoveField(
            model_name='bloglistingpage',
            name='introduction',
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='banner_call_to_action_button_link',
            field=models.ForeignKey(blank=True, help_text='Select an optional page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='banner_call_to_action_button_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='banner_headline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='banner_small_text',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
