# Generated by Django 3.1.8 on 2021-05-03 17:39

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210503_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='category',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(to='blog.BlogCategory'),
        ),
    ]
