# Generated by Django 3.1.8 on 2021-05-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210503_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='banner_call_to_action_button_link',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='banner_call_to_action_button_text',
        ),
        migrations.RemoveField(
            model_name='bloglistingpage',
            name='banner_call_to_action_button_link',
        ),
        migrations.RemoveField(
            model_name='bloglistingpage',
            name='banner_call_to_action_button_text',
        ),
    ]
