# Generated by Django 3.1.8 on 2021-05-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210503_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingpage',
            name='read_more_button_text',
            field=models.CharField(default='Read Article', max_length=20, verbose_name="Text for 'Read More' button"),
        ),
    ]
