# Generated by Django 3.1.8 on 2021-05-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210503_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Set automatically'),
        ),
    ]
