# Generated by Django 3.1.8 on 2021-05-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210504_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='banner_headline',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='banner_small_text',
        ),
    ]
