# Generated by Django 3.1.8 on 2021-04-20 17:51

import core.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.core.fields.StreamField([('two_column_block', core.blocks.TwoColumnBaseBlock())], blank=True, verbose_name='Page body'),
        ),
    ]
