# Generated by Django 3.1.8 on 2021-05-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_auto_20210503_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='banner_call_to_action_button_link',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='banner_call_to_action_button_text',
        ),
    ]
