# Generated by Django 3.1.8 on 2021-04-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0006_auto_20210413_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='author_description',
            field=models.CharField(blank=True, help_text="Optional - Brief description of referee ('Mother of a student' etc)", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(help_text='Name of referee', max_length=60),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ForeignKey(help_text='Photo of author (displayed at 25x25)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
