# Generated by Django 3.1.8 on 2021-04-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.servicetype'),
        ),
    ]
