# Generated by Django 3.1.8 on 2021-04-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_testimonial_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
