# Generated by Django 3.1.8 on 2021-04-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0012_auto_20210414_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='seo_page_ptr',
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
    ]
