# Generated by Django 3.1.8 on 2021-04-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210414_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='seo_page_ptr',
            new_name='seopage_ptr',
        ),
    ]
