# Generated by Django 3.1.8 on 2021-04-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seopage'),
        ('home', '0018_auto_20210415_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='summary',
        ),
        migrations.AddField(
            model_name='homepage',
            name='seopage_ptr',
            field=models.OneToOneField(auto_created=True, default=200, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.seopage'),
            preserve_default=False,
        ),
    ]
