# Generated by Django 3.1.8 on 2021-04-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0019_auto_20210415_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='seopage_ptr',
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=100, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summary',
            field=models.TextField(default='test', help_text='A summary of the page to be used on index pages.                      If Search Description is left blank, this text will be used on searh results and link previews.'),
            preserve_default=False,
        ),
    ]
