# Generated by Django 3.1.8 on 2021-04-16 13:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210415_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('headline', wagtail.core.blocks.CharBlock(required=False)), ('small_text', wagtail.core.blocks.CharBlock(required=False)), ('call_to_action_button_text', wagtail.core.blocks.CharBlock(required=False)), ('call_to_action_button_link', wagtail.core.blocks.PageChooserBlock(required=False))], verbose_name='Page body'),
            preserve_default=False,
        ),
    ]
