# Generated by Django 3.1.8 on 2021-04-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homepage_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner',
        ),
    ]
