# Generated by Django 3.1.8 on 2021-04-19 13:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210419_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('richtext_block', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'hr', 'center', 'right']))])), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=True)), ('caption', wagtail.core.blocks.CharBlock(label='Image Caption (optional)', required=False)), ('attribution', wagtail.core.blocks.CharBlock(label='Image Attribution (optional)', required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(label='Quote')), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='Optional Attribution', required=False))])), ('link_button', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(blank=False, label='Button Text', max_length=50, null=False)), ('internal_page', wagtail.core.blocks.PageChooserBlock(label='Link to internal page', required=False)), ('url_link', wagtail.core.blocks.CharBlock(label='Link to external site or internal URL', required=False)), ('appearance', wagtail.core.blocks.ChoiceBlock(choices=[('btn-primary', 'Standard Button'), ('btn-btn-secondary', 'Secondary Button'), ('btn-link', 'Text Only'), ('btn-success', 'Success Button'), ('btn-danger', 'Danger Button'), ('btn-warning', 'Warning Button'), ('btn-info', 'Info Button'), ('btn-light', 'Light Button'), ('btn-dark', 'Dark Button')], label='Button Appearance', max_length=15)), ('placement', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], label='Button Placement', max_length=15)), ('size', wagtail.core.blocks.ChoiceBlock(choices=[('btn-sm', 'Small'), (' ', 'Standard'), ('btn-lg', 'Large')], label='Button Size', max_length=10))]))], blank=True, verbose_name='Page body'),
        ),
    ]
