# Generated by Django 3.1.8 on 2021-05-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_from_email', models.CharField(max_length=80, verbose_name='Sending Email Address')),
                ('host', models.CharField(max_length=80, verbose_name='Mail Server')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('use_tls', models.BooleanField(default=False, help_text='Use only TLS or SSL', verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use only TLS or SSL', verbose_name='Use SSL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
