# Generated by Django 3.1.8 on 2021-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='default_from_email',
            field=models.CharField(max_length=80, null=True, verbose_name='Sending Email Address'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='host',
            field=models.CharField(max_length=80, null=True, verbose_name='Mail Server'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='port',
            field=models.IntegerField(null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='Use only TLS or SSL', verbose_name='Use SSL'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='Username'),
        ),
    ]
