# Generated by Django 3.1.8 on 2021-05-01 19:12

from django.db import migrations
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20210501_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='password',
            field=site_settings.models.PasswordModelField(max_length=30, null=True, verbose_name='Password'),
        ),
    ]
