# Generated by Django 3.1.8 on 2021-05-02 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('site_settings', '0004_auto_20210501_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('receipt_footer_content', wagtail.core.fields.RichTextField(help_text='Text for the Email Signature', verbose_name='Email Footer Content')),
                ('intro_image', models.ForeignKey(blank=True, help_text='Image to display in left column of Email Signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image for Left Column')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
