# Generated by Django 3.1.8 on 2021-05-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_emailfootersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailFooterSettings',
        ),
    ]
