# Generated by Django 3.1.8 on 2021-05-02 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_settings', '0006_delete_emailfootersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('signature_name', models.CharField(help_text='Used to identify this signature', max_length=30, verbose_name='Email Signature Title')),
                ('signature_content', wagtail.core.fields.RichTextField(help_text='Text for the Email Signature', verbose_name='Email Signature Content')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
                ('signature_image', models.ForeignKey(blank=True, help_text='Image to display in left column of Email Signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image for Left Column')),
            ],
            options={
                'verbose_name': 'Email Signature',
                'verbose_name_plural': 'Social Media Links',
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
